=== Sohalt/emacspeak/trunk/emacspeak/etc/applications.dtd
<?xml version="1.0" ?>
<!ELEMENT  applications  (category)+                              >
<!--         caption    Descriptive caption                        -->
<!ATTLIST  applications
             caption    CDATA                              #REQUIRED >

<!--                    Contains applications of a specific named
                        category                                   -->
<!ELEMENT  category     (application)+                               >
<!--         name       Name of this category. Pick a descriptive
                        name with multiple words, with the first word
                        capitalized.                               -->
<!ATTLIST  category
             name       CDATA                              #REQUIRED >
<!--                    Contains information about an application. -->
<!ELEMENT  application  (#PCDATA)                                      >
<!--         name       Name of this application. Pick a short single
                        word hyphenated if necessary, all lower
                        case.                                      -->
<!ATTLIST  application
             name       CDATA                              #REQUIRED >

=== Sohalt/emacspeak/emacspeak/etc/applications.xml
<?xml version="1.0" encoding="utf-8"?>
<!--$Id$-->
<!DOCTYPE applications PUBLIC " applications // t. v. raman 1.0" "applications.dtd">
<?xml-stylesheet href="file:////home/raman/emacs/lisp/emacspeak/etc/applications.xsl"
type="text/xsl"?>
<applications caption="Speech-enabled applications  on the Emacspeak audio desktop.">
  <preamble title="Emacspeak --The Complete Audio Desktop"/>
  <introduction>
    <h1>Speech-enabled Applications On The Emacspeak Desktop </h1>
    <p>
      This document catalogs the speech-enabled applications available on the Emacspeak desktop.
      Note that depending on your Emacs installation,
      you may need to download and install extra applications to
      avail yourself of all of the features of the Emacspeak audio
      desktop.
      Emacs applications can be located via the various Emacs Lisp
      archives or by using popular WWW search engines. For
      one such comprehensive index, see
      the <a href="http://anc.ed.ac.uk/~stephen/emacs/ell.html"
      shape="rect">
the Emacs Lisp Library</a>.
This is also available through the 
<a href="http://www.emacswiki.org/cgi-bin/wiki/WikifiedEmacsLispList">Emacs Wiki</a>
      
    </p>
    <h2>Speech-Enabled Applications</h2>
  </introduction>
  <category name="documentation">
    <application name="info">
      Emacs' online hypertext documentation system.
      Emacspeak uses audio formatting to highlight menus and hyperlinks.
    </application>
    <application name="help">
      Speech-enabled online help across the audio
    desktop.</application>
    <application name="man">
      UNIX online manual browser with full aural highlighting and
    structured browsing.</application>
    <application name="howto">
    Emacspeak wizard for browsing Linux HOWTO documents.</application>  
  </category>
  <category name="desktop">
    <application name="ido">
      Efficiently find buffers and files on the audio desktop
      --- the IDo way.
    </application>
    <application name="ibuffer">
      Tool for locating open buffers on the audio desktop.
    </application>
    <application name="iswitchb">
      Quickly switch to buffers on the audio desktop.
    </application>
    <application name="bs">
      Tool for locating open buffers on the audio desktop.
    </application>
    <application name="buff-menu">
    Browsing and selecting buffers on the audio desktop.</application>
    <application name="buff-sel">
      Interactive selection of buffers on the audio desktop.
    </application>
    <application name="yasg">
      Pattern-based selection of open buffers.
    </application>
    <application name="speedbar">
      Context-sensitive browsing tool.
      Provides seamless browsing of the entire file system or a
      single file with the same consistent interface.
    </application>
    <application name="sawfish">
      Speech-enables the Sawfish window-manager.
    </application>
  </category>
  <category name="finders">
    <application name="dired">
      Browse and operate on files and folders.
    </application>
    <application name="wdired">
      Edit filenames within dired as a means of moving and
      renaming files.
    </application>
    <application name="ffap">
      Find file or url at point.
    </application>
    <application name="locate">
      File browser interface for finding files.
    </application>
    <application name="find-dired">
      Seamless integration between the file browser and 
      finder.
    </application>
    <application name="find-grep">
      Using grep with find. also, se igrep.
    </application>
    <application name="efs">
      Front-end to remote file access using an FTP
    back-end.</application>
    <application name="tramp">
    Front-end to remote file access using SSH backend.</application>
    <application name="finder">
      Package browser for locating  installed  applications.
    </application>
    <application name="rpm">
      Client for browsing installed RPM packages.
  </application></category>
  <category name="web">
    <application name="w3">
      Standards-compliant WWW browser with Aural CSS
    support.</application>
    <application name="w3m">
      Light-weight WWW browser.
    Does not support table navigation, CSS or Aural CSS, but can be fast and light-weight.</application>
    <application name="url-template">
      Emacspeak client  that provides programmable  URL templates.
      Pre-defined templates offer easy access to W3C mailing
      lists, CNN sites etc.
    </application>
    <application name="websearch">
      Emacspeak websearch client with single click access to
      popular search engines.
      Once selected,  the searcher prompts for the relevant input,
      performs the search, and speaks the  result.
      In addition, see the Web wizards in <a
      href="#wizards">Emacspeak Wizards</a>.
    </application>
    <application name="xslt">
      Ability to apply XSL transforms to Web content before it is
      displayed.
    </application>
    <application name="lynx">
      Single key interface for invoking lynx in an appropriately
      customized terminal buffer.
    </application>
    <application name="net-utils">
      Front-end to networking tools.
    </application>
    <application name="babel">
      Access Internet  translation services.
    </application>
  </category>
  <category name="Messaging">
    <application name="vm">
      Mail reader featuring full mime support.
    </application>
    <application name="bbdb">
      Manages email addresses and other contact information by
      seamlessly integrating with messaging applications.
    </application>
    <application name="eudc">
      Universal Directory Client including LDAP support and
    seamless integration with messaging applications.</application>
    <application name="gnus">
      Usenet news and email client
      with support for exotic information backends such as
    Slashdot etc.</application>
    <application name="newsticker">
      Speech-enabled NewsTicker, a native Emacs RSS reader.
    </application>
    <application name="amphetadesk">
      Emacs front-end to AmphetaDesk
    </application>
    <application name="rss">
      Speech-enabled RSS viewer for RSS 0.9, RSS 1.0 and RSS 2.0
    </application>
    <application name="message">
      Email composition   from
    within other applications.</application>
    <application name="supercite">
    Enables flexible citations when composing  email.</application>
    <application name="tnt">
      Instant Messenger (AIM) client,
      with support for multiple parallel chat
    sessions.</application>
    <application name="erc">
      Internet Relay Chat (IRC) client
    with  voice locking support and parallel chat sessions.</application>
    <application name="imcom">
      IMCom is a Python-based jabber client.
      Module emacspeak-imcom speech-enables IMCom with full audio
      formatting support.
      Chat sessions can be viewed within W3  with full ACSS support.
    </application>
    <application name="gnuyahoo">
      GNUYahoo is a Yahoo messenger client.
    </application>
    <application name="mspools">
      Interface for working with multiple mail spools;
      allows easy browsing of automatically archived mail.
    </application>
    <application name="mh-e">
    Interface to the MH suite of email tools.</application>
    <application name="rmail">
    Email client.</application>
  </category>
  <category name="calendaring">
    <application name="calendar">
      Desktop calendar with an integrated appointment book.
    </application>
    <application name="diary">
      Speech-enabled diary via EDiary.
    </application>
    <application name="appointments">
      Speech-enabled appointments via the Emacs calendar.
    </application>
    <application name="todo">
      Speech-enabled ToDo Lists.
    </application>
  </category>
  <category name="shell">
    <application name="shell">
      Runs interactive command interpreters like BASH and TCSH.
    </application>
    <application name="ansi-colors">
      Applies Aural CSS ACSS properties to convert ansi color
      codes to appropriate voice changes to produce
      audio formatted output.
    </application>
    <application name="eterm">
      Speech-enabled  terminal client for running full-screen
      applications like VI, Lynx and PINE.
    </application>
    <application name="ssh">
    Front-end to SSH.</application>
    <application name="eshell">
      Command shell implemented in Emacs Lisp, making it
      independent of the underlying operating system.
    </application>
    <application name="comint">
      Support for running generic command interpreters.
    </application>
    <application name="xml-shell">
      Interactive shell for browsing XML structures via libxml and
      XMLLint.
    </application>  
  </category>
  <category name="taskbar">
    <application name="view-process">
      Front-end for monitoring and controlling  processes.
    </application>
    <application name="analog">
      Analog.el provides a log analyzer that can be customized to
      display system log files with a few convenient
    keystrokes.</application>  
  </category>
  <category name="Multimedia">
    <application name="aumix">
      Emacspeak front-end for configuring  the 
      auditory display.
    </application>
    <application name="cd-tool">
    Control CD player from anywhere on the audio desktop.</application>
    <application name="freeamp">
      Ubiquitous access to Freeamp mp3  with a single
      keystroke.
    </application>
    <application name="mpg123">
      Play mp3 files, with keyboard access to  all   functions.
    </application>
    <application name="realaudio">
      Play RealAudio, RealMedia and mp3  streams. Includes
      presets  for single click access to
      favorite streams.
    </application>
    <application name="mplayer">
